core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
     path("", views.HomeView.as_view(), name="home"),
    ]
    

ecommerce/urls.py
from django.urls import path
from . import views

app_name = "ecommerce"

urlpatterns = [

    path('items/', views.ItemsView.as_view(), name='items'),
    path('item/<slug:slug>/', views.ItemView.as_view(), name='item'),
	path('items/add-or-remove/', views.add_or_remove_item, name='add_or_remove'),
	path('checkout/', views.CheckoutView.as_view(), name="checkout"),
	path('pay/', views.stripe_payment, name="pay"),
	path('cart/', views.CartView.as_view(), name="cart"),
	path('orders/', views.OrdersView.as_view(), name="orders"),
	path('order/<int:id>/', views.OrderView.as_view(), name="order"),
	path('update-source/', views.update_source, name="update-source"),
	]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')), # Our bespoke apps
    path('', include('ecommerce.urls', namespace="ecommerce")),
    path('', include('users.urls', namespace="users")),
    path("__debug__/", include('debug_toolbar.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

from djmoney.models.fields import MoneyField
from django_extensions.db.models import (
    TimeStampedModel,
    ActivatorModel,
    TitleSlugDescriptionModel # Adds a title description and a slug to our model
)


class Item(
    TimeStampedModel,
    ActivatorModel ,
    TitleSlugDescriptionModel,
    models.Model):

    """
    ecommerce.Item
    Stores a single item entry for our shop
    """

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'
        ordering = ["id"]
    
    image = models.ImageField(default='default_item_image.jpg', upload_to='items', null=True, blank=True)

    stock = models.IntegerField(default=1)
    variable_price = MoneyField(
        max_digits=14, 
        decimal_places=2, 
        default_currency='GBP', # You can default to your local currency
        null=True, 
        blank=True)

    def amount(self):
        amount = int(self.variable_price.amount * 100)
        return amount

    def get_absolute_url(self):
        return f'/item/{self.slug}/'
    

class CartItemManager(models.Manager):
    """
    A Manager for Cart item objects
    """
    def get_query_set(self):
        return self.get_queryset()

    def clear_items(self, user):
        '''
        Used to remove all cart items after payment is processed
        Useage - CartItem.objects.clear_items(auth.User)
        '''
        qs = self.get_query_set().filter(
            user = user
        )

        for q in qs:
            q.delete()



class CartItem(
    TimeStampedModel,
    ActivatorModel ,
    models.Model):
    """
    ecommerce.CartItem
    Stores a single item entry, related to :model:`ecommerce.Item` and
    :model:`auth.User`.
    """
    class Meta:
        verbose_name = 'Item for cart'
        verbose_name_plural = 'Item for cart'
        ordering = ["id"]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    item = models.ForeignKey(Item, null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def amount(self):
        amount = self.item.amount() * self.quantity
        return amount

    objects = CartItemManager()


class Cart(
    TimeStampedModel,
    ActivatorModel ,
    models.Model):
    """
    ecommerce.Cart
    This is a Users Shopping cart, related to :model:`auth.User`.
    """

    class Meta:
        verbose_name = 'User cart'
        verbose_name_plural = 'User cart'
        ordering = ["id"]

    user = models.OneToOneField(User, on_delete=models.CASCADE)   
    items = models.ManyToManyField(CartItem, blank=True)

    def item_count(self):
        count = 0
        for obj in self.items.all():
            count += obj.quantity
        return count

    def amount(self):
        count = 0
        for obj in self.items.all():
            count += obj.amount()
        return int(count)

    def add_or_remove(self, action, object):
        '''
        Used to easily add or remove users to the cart model
        '''
        match action:
            case "add":
                if object not in self.items.all():
                    self.items.add(object)
            case "remove":
                self.items.remove(object)
        self.save()

    def item_check(self, item):
        '''
        Checks if an item is in the User cart
        '''
        cartitems = [i.item  for i in self.items.all()]
        if item in cartitems:
            return True
        return False

    def qty_check(self, item):
        try:
            cart_item = CartItem.objects.get(item = item, user = self.user)
            return cart_item.quantity
        except CartItem.DoesNotExist:
            return 0.0




class Source(
    TimeStampedModel,
    ActivatorModel ,
    models.Model):
    """
    ecommerce.Source
    Stores Stripe ID's for sources (payment methods).
    """
    class Meta:
        verbose_name = 'Source'
        verbose_name_plural = 'Sources'
        ordering = ["id"]
    stripe_id = models.CharField(max_length=100)
    is_default = models.BooleanField(default=False)



class Line(
    TimeStampedModel,
    ActivatorModel ,
    models.Model):

    '''
    ecommerce.Line
    Stores a single line entry, related to :model:`ecommerce.Item` and
    :model:`auth.User`.
    '''
    class Meta:
        verbose_name = 'Invoice Line'
        verbose_name_plural = 'Invoice Lines'
        ordering = ["id"]

    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)   
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, blank=True, null=True)
    amount = MoneyField(max_digits=14, decimal_places=2, default_currency='GBP', null=True, blank=True)
    stripe_id = models.CharField(max_length=100)
    quantity = models.IntegerField(default=1, blank=True,null=True)


class Invoice(
    TimeStampedModel,
    ActivatorModel ,
    models.Model):
    '''
    ecommerce.Invoice
    Stores a single invoice entry, related to :model:`ecommerce.Line`,
    :model:`ecommerce.Source` and :model:`auth.User`.
    '''
    class Meta:
        verbose_name = 'User Invoice'
        verbose_name_plural = 'User Invoices'
        ordering = ["id"]

    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)   
    source = models.ForeignKey(Source, on_delete=models.SET_NULL, blank=True, null=True) 
    stripe_id = models.CharField(max_length=100)

    lines = models.ManyToManyField(Line, blank=True)

    def item_count(self):
        count = 0
        for obj in self.lines.all():
            count += obj.quantity
        return count

    def amount(self):
        count = 0
        for obj in self.lines.all():
            count += obj.buy_amount * obj.quantity
        return count

    def wallet(self):
        wallet = Wallet.objects.for_source(self.source)
        return wallet

class WalletManager(models.Manager):
    """
    A Manager for Wallet objects
    """
    def get_query_set(self):
        return self.get_queryset()

    def for_source(self, source):
        """
        Returns a Wallet objects queryset for a given source model.
        Usage:
            Source = Source.objects.first()
            Wallet.objects.for_source(Source)
        """
        qs = self.get_query_set().filter(
            sources=source
        )

        return qs

class Wallet(TimeStampedModel, ActivatorModel):
    '''
    ecommerce.Wallet
    Stores a single wallet entry related to :model:`ecommerce.Invoice`,
    :model:`ecommerce.Source` and :model:`auth.User`.
    '''
    class Meta:
        verbose_name = 'User Wallet'
        verbose_name_plural = 'User Wallets'
        ordering = ["id"]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_id = models.CharField(max_length=100, blank=True, null=True)
    invoices = models.ManyToManyField(Invoice, blank=True)
    sources = models.ManyToManyField(Source, blank=True)

    objects = WalletManager()

ecommerce/views.py
from django.views import generic
from django.shortcuts import redirect, reverse
from django.conf import settings
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseBadRequest
from . models import Item, CartItem, Source, Line
from .utils import EcommerceManager
from functools import wraps
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

def ajax_required(f):
    """
    AJAX request required decorator
    """
    def wrap(request, *args, **kwargs):
        if not request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return HttpResponseBadRequest('Invalid request')
        return f(request, *args, **kwargs)

    wrap.__doc__ = f.__doc__
    wrap.__name__ = f.__name__
    return wrap


def empty_cart(function):
    """
    Decorator for views that checks if a user cart is empty.
    redirect user to /items/
    """
    @wraps(function)
    def wrap(request, *args, **kwargs):
        user = request.user
        ecommerce_manager = EcommerceManager(user = user)
        cart_obj = ecommerce_manager.cart_object()
        if cart_obj.items.all().count() == 0:
            return redirect(reverse('ecommerce:cart'))
        return function(request, *args, **kwargs)
    return wrap

class ItemsView(generic.ListView):
    """
    Listview that displays all active items in shop.

    Queryset of :model:`ecommerce.Item`.

    **Template:**

    :template:`ecommerce/items.html`
    """
    model = Item
    template_name = "ecommerce/items.html"
    paginate_by: int = 10

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        qs = Item.objects.active().filter(stock__gt=0)
        return qs

class ItemView(generic.DetailView):
    """
    Listview that displays individual item in shop.

    An instance of :model:`ecommerce.Item`.

    **Template:**

    :template:`ecommerce/item.html`
    """
    model = Item
    template_name = "ecommerce/item.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@login_required
@ajax_required
def add_or_remove_item(request):
    """
    Function used to handle the adding and removing of items to cart.
    This is also where we handle stock.
    """
    data = {"result": "Error","message": "Something went wrong","redirect": False}
    try:
        obj_id = request.POST["object_id"]
    except (KeyError, ValueError):
        data["message"] = 'Invalid request'
        return JsonResponse(data)

    try:
        action = request.POST["action"]
    except (KeyError, ValueError):
        data["message"] = 'Invalid request'
        return JsonResponse(data)

    try:
        item = Item.objects.get(id = obj_id)
    except Item.DoesNotExist:
        data["message"] = 'Object does not exist'
        return JsonResponse(data)
    
    quantity = request.POST.get("object_quantity", 0)
    quantity = int(quantity)
    stock = item.stock
    cart_item, created = CartItem.objects.get_or_create(user = request.user, item = item)
    ecommerce_manager = EcommerceManager(request.user)
    cart = ecommerce_manager.cart_object()

#   Released in python 10 
    match action:
        case "remove":
            cart.add_or_remove(action, cart_item)
            qty = cart_item.quantity
            stock = stock + qty
            item.stock = stock
            item.save()
            cart_item.quantity = 0
            cart_item.save()
        case "add":
            if stock < quantity:
                data["message"] = 'Not enough stock'
                return JsonResponse(data)
            qty = cart_item.quantity
            cart.add_or_remove("add", cart_item)
            stock = stock - quantity
            item.stock = stock
            item.save()
            qty += quantity
            cart_item.quantity = qty
            cart_item.save()
    cart.save()

    item_count=cart.item_count()
    item_total_price=cart.amount()
    item_stock=stock
    data = {
            "result": "Success",
            "message": f'{item.title} has been {action}d to your cart',
            "redirect": False,
            "data": {
                "status": action,
                "item_count": item_count,
                "item_total_price": item_total_price,
                "stock": item_stock
            }
        }
    return JsonResponse(data)


class CartView(generic.TemplateView):
	"""
    TemplateView to display all items in a users cart.

    **Context**

    Stripe publishable key.

    **Template:**

    :template:`ecommerce/cart.html`
    """
	template_name = "ecommerce/cart.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["stripe_key"] = settings.STRIPE_PUBLISHABLE_KEY
		return context

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)



class CheckoutView(generic.TemplateView):
    """
    TemplateView to allow users to pay for all items in their cart.

    **Context**

    Stripe publishable key.
    sources - Queryset of :model:`ecommerce.Source`.
    default_card - An instance of :model:`ecommerce.Source`.

    **Template:**

    :template:`ecommerce/checkout.html`
    """
    template_name = "ecommerce/checkout.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["stripe_key"] = settings.STRIPE_PUBLISHABLE_KEY
        ecommerce_manager = EcommerceManager(self.request.user)
        context["sources"] = ecommerce_manager.get_source_data()
        try:
            context["default_card"] = ecommerce_manager.wallet_object().sources.get(is_default=True)
        except Source.DoesNotExist:
            context["default_card"] = ""
        return context

    @method_decorator(login_required)
    @method_decorator(empty_cart)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

@login_required
@ajax_required
def stripe_payment(request):
    """
    Function to handle the user payment
    """
    data = {"result": "Error","message": "Something went wrong","redirect": False}
    token = request.POST.get("stripeToken", None)
    source_id = request.POST.get("card_id", None)
    ecommerce_manager = EcommerceManager(request.user, token=token, source_id = source_id)
    invoice = ecommerce_manager.post_invoice()
    match invoice["status"]:
        case "200"|"201"|"202"|"203"|"204":
            data["redirect"] = "/"
            data["result"] = "Success"
            data["message"] = invoice["message"]
        case _:
            data["message"] = invoice["message"]
    return JsonResponse(data)


@login_required
@ajax_required
def update_source(request):
    """
    Function to source updates
    """
    data = {"result": "Error","message": "Something went wrong","redirect": False}
    card_id = request.POST.get("card_id", None)
    ecommerce_manager = EcommerceManager(request.user)
    ecommerce_manager.put_source(card_id)
    data["redirect"] = "/checkout/"
    data["result"] = "Success"
    data["message"] = "Your source has been updated"

    return JsonResponse(data)


class OrdersView(generic.ListView):
    """
    Listview that displays all orders made by user.

    Queryset of :model:`ecommerce.Line`.

    **Template:**

    :template:`ecommerce/orders.html`
    """
    model = Line
    template_name = "ecommerce/orders.html"
    paginate_by: int = 10

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        qs = Line.objects.active().filter(user = self.request.user)
        return qs

class OrderView(generic.DetailView):
    """
    DetailView that displays individual order.

    An instance of :model:`ecommerce.Line`.

    **Template:**

    :template:`ecommerce/order.html`
    """
    model = Line
    template_name = "ecommerce/order.html"

    def get_object(self):
        return Line.objects.get(id=self.kwargs['id'])

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

templates/ecommerce/cart.html
{% extends 'base/base.html' %}
{% load static ecommerce_tags mathfilters %}

{% block content %}

<h1>Cart</h1>


<div class="row">
  <div class="col-75">
    {% for object in request.user.cart.items.all %}
    <div class="column item-list-{{object.item.id}}">
      <div class="card">
        
        <img src="{{object.item.image.url}}" alt="{{object.item.title}}" style="width:100%">
        <h2>{{object.item.title}}</h2>
        <p class="price">{{object.item.price}}</p>
        <p>{{object.item.description}}</p>
        <p>  
          <form>
            <div class="form-group row">
              <div class="col-sm-2">
              {% item_button_v2 object.item %}
              </div>
              <label for="quantity" class="col-sm-4 col-form-label">Quantity</label>
              <div class="col-sm-6">
                <input readonly class="form-control-plaintext" name="quantity-{{object.id}}" id="quantity-input-{{object.id}}" class="quantity-input-{{object.id}}" value="{{object.quantity}}">
              </div>
            </div>
            
          </form>
        </p>
        <p><a class="btn btn-primary" href="{{object.item.get_absolute_url}}" >&#x2607;</a></p>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="col-25">
    <div class="container">
      <h4>Summary
        <span class="price" style="color:black">
          <i class="fa fa-cart-shopping"></i>
          <b class="item-count">{{request.user.cart.item_count}}</b>
        </span>
      </h4>
      <hr>
      <p>Total <span class="price" style="color:black"><b class="item-total-price">£{{request.user.cart.amount|div:100}}</b></span></p>
      <p><a class="btn btn-success" href="{% url 'ecommerce:checkout' %}">Go to checkout</a></p>
    </div>
  </div>
</div>
{% endblock %}

templates/ecommerce/checkout.html
{% extends 'base/base.html' %}
{% load static ecommerce_tags mathfilters djmoney %}

{% block extend_head %}
<link rel="stylesheet" href="{% static 'stripe.css' %}">
{% endblock %}

{% block extend_foot %}
<script src="https://js.stripe.com/v3/"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="{% static 'stripe.js' %}" defer></script>
<script type="text/javascript">
    var stripe_key = '{{stripe_key|safe}}'
</script>
{% endblock %}

{% block content %}

<h1>Checkout</h1>

<div class="row">
    <div class="col-75">
      <div class="container">
        {% if sources.has_sources %}
        <h4>Select a card to use</h4>
        <table id="saved-cards">
            <thead>
            <tr>

                <th>Type</th>
                <th>Card Number</th>
                <th>Exp date</th>
                <th>Is default</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for s in sources.sources %}
            <tr>

                <td>{{s.type}}</td>
                <td>{{s.card}}</td>
                <td>{{s.exp}}</td>
                <td>{{s.default}}</td>
                <td>{% if not s.default %}<a class="btn btn-warning source" value="{{s.stripe_id}}" >Make default</a>{% endif %}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <br>
        <a class="btn btn-warning pay" value="{{default_card.stripe_id}}" >Pay <i class="item-total-price">{{request.user.cart.amount|div:100}}</i> with default card</a>
        <br>

        {% endif %}
        <br>
        <h4>Pay with new card</h4>
        <form id="payment-form" style="width: 100%">
            {% csrf_token %}
            <div id="card-element"><!--Stripe.js injects the Card Element--></div>
            <button id="submit" type="submit">
            Pay <i class="item-total-price">£{{request.user.cart.amount|div:100}}</i> with new card
            </button>
            <p id="card-error" role="alert"></p>
            <p class="result-message hidden">
            Payment succeeded, see the result in your
            <a href="" target="_blank">Stripe dashboard.</a> Refresh the page to pay again.
            </p>
        </form>
      </div>
    </div>
  
    <div class="col-25">
      <div class="container">
        <h4>Cart
          <span class="price" style="color:black">
            <i class="fa fa-cart-shopping"></i>
            <b class="item-count">{{request.user.cart.item_count}}</b>
          </span>
        </h4>
        {% for object in request.user.cart.items.all %}
        <p class="item-list-{{object.item.id}}">{% item_button_v2 object.item %}
            <a href="{{object.item.content_object.get_absolute_url}}">{{object.item.content_object.title}}</a> <span class="price">£{{object.amount|div:100}}</span></p>
        {% endfor %}
        <hr>
        <p>Total <span class="price" style="color:black"><b class="item-total-price">£{{ request.user.cart.amount|div:100 }}</b></span></p>
      </div>
    </div>
  </div>
{% endblock %}

templates/ecommerce/item.html
{% extends 'base/base.html' %}
{% load static ecommerce_tags %}

{% block content %}

<h3>Item - {{object.title}}</h3>

<div class="container">
    <div class="row">
        <div class="col-6">
            <form>
                <label for="stock">Price per item</label>
                <input type="text" readonly value="{{object.variable_price}}">
                <label for="stock">Stock</label>
                <input type="text" name="stock-{{object.id}}" id="stock-input-{{object.id}}" class="stock-input-{{object.id}}" readonly value="{{object.stock}}">
                <label for="quantity">Quantity</label>
                <input type="number" min="1" name="quantity-{{object.id}}" id="quantity-input-{{object.id}}" class="quantity-input-{{object.id}}" value="0">
            </form>
        </div>
    <div class="col-6">
        <img src="{{object.image.url}}" alt="{{object.title}}" class="image">
    </div>
    
</div>
    {% item_button item %}
</div>
{% endblock %}

templates/ecommerce/item_button.html
{% load static %}

{% comment %} this adds an icon that, when clicked, allows users to add items to cart!! {% endcomment %}
<a class="item btn btn-success" model="{{ target_model }}" id="target_{{ object_id }}" action="add">
	<i class="item-{{object_id}} fa-solid fa-cart-plus"></i>
	<span class="item-count-{{ object_id }}"></span>
</a>

templates/ecommerce/item_button_v2.html
{% load static %}

{% comment %} this adds an icon that, when clicked, allows users to remove items from cart!! {% endcomment %}
<a style="color:red;" class="item" model="{{ target_model }}" id="target_{{ object_id }}" action="remove"><i class="item-{{object_id}} fa-solid fa-close"></i></a>

templates/ecommerce/items.html
{% extends 'base/base.html' %}
{% load static  %}


{% block content %}
<h1>Shop items</h1>
<div class="row card-column">
  {% for object in object_list %}
  <div class="column">
    <div class="card">
      <img src="{{object.image.url}}" alt="{{object.title}}" style="width:100%">
      <h2>{{object.title}}</h2>
      <p class="price">{{object.variable_price}}</p>
      <p>{{object.description}}</p>
      <p><a class="btn btn-primary" href="{{object.get_absolute_url}}" >&#x2607;</a></p>
    </div>
  </div>
  {% endfor %}

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
</div>
{% endblock %}

templates/ecommerce/order.html
{% extends 'base/base.html' %}
{% load static ecommerce_tags %}

{% block content %}

<h3>Order - {{object.item.title}}</h3>

<div class="container">
    <div class="row">
        <div class="col-6">
            <form>
                <label for="date">Date</label>
                <input type="text" readonly value="{{object.created}}">
                <label for="stock">Total price</label>
                <input type="text" readonly value="{{object.amount}}">
                <label for="quantity">Quantity</label>
                <input type="number" value="{{object.quantity}}">
            </form>
        </div>
    <div class="col-6">
        <img src="{{object.item.image.url}}" alt="{{object.item.title}}" class="image">
    </div>
    
</div>
</div>
{% endblock %}

templates/ecommerce/orders.html
{% extends 'base/base.html' %}
{% load static  %}


{% block content %}
<h1>You Orders</h1>
<div class="row card-column">
  {% for object in object_list %}
  <div class="column">
    <div class="card">
      <img src="{{object.item.image.url}}" alt="{{object.item.title}}" style="width:100%">
      <h2>{{object.item.title}}</h2>
      <p class="price">{{object.amount}}</p>
      <p>{{object.item.description}}</p>
      <p><a class="btn btn-primary" href="{% url 'ecommerce:order' id=object.item.id %}" >&#x2607;</a></p>
    </div>
  </div>
  {% endfor %}

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
</div>
{% endblock %}